INSERT INTO sample (name,question) VALUES ('赤坂　晴樹','test1な人は誰？');
INSERT INTO sample (name,question) VALUES ('石川　生芽','test2な人は誰？');
INSERT INTO sample (name,question) VALUES ('石田　悠菜','test3な人は誰？');
INSERT INTO sample (name,question) VALUES ('井上　陽介','test4な人は誰？');
INSERT INTO sample (name,question) VALUES ('加賀谷　星也','test5な人は誰？');
INSERT INTO sample (name,question) VALUES ('香取　菜々子様','test6な人は誰？');
INSERT INTO sample (name,question) VALUES ('金井　千乃','test7な人は誰？');
INSERT INTO sample (name,question) VALUES ('川岸　小雪','test8な人は誰？');
INSERT INTO sample (name,question) VALUES ('川﨑　なゆ美','test9な人は誰？');
INSERT INTO sample (name,question) VALUES ('河守　英実','test10な人は誰？');
INSERT INTO sample (name,question) VALUES ('北川　千紘','test11な人は誰？');
INSERT INTO sample (name,question) VALUES ('北嶋　伶那','test12な人は誰？');
INSERT INTO sample (name,question) VALUES ('河野　朱里','test13な人は誰？');
INSERT INTO sample (name,question) VALUES ('後藤　未来','test14な人は誰？');
INSERT INTO sample (name,question) VALUES ('小西　一輝','test15な人は誰？');
INSERT INTO sample (name,question) VALUES ('坂井　夏海','test16な人は誰？');
INSERT INTO sample (name,question) VALUES ('椎名　美紀','test17な人は誰？');
INSERT INTO sample (name,question) VALUES ('菅谷　彩乃','test18な人は誰？');
INSERT INTO sample (name,question) VALUES ('瑞慶覧　康平','test19な人は誰？');
INSERT INTO sample (name,question) VALUES ('髙橋　大希','test20な人は誰？');
INSERT INTO sample (name,question) VALUES ('髙橋　舞帆','test21な人は誰？');
INSERT INTO sample (name,question) VALUES ('塚田　夏美','test22な人は誰？');
INSERT INTO sample (name,question) VALUES ('中野　郁実','test23な人は誰？');
INSERT INTO sample (name,question) VALUES ('百瀬　天哉','test24な人は誰？');
INSERT INTO sample (name,question) VALUES ('山﨑　菜々','test25な人は誰？');
INSERT INTO sample (name,question) VALUES ('山本　観月','test26な人は誰？');
INSERT INTO sample (name,question) VALUES ('吉田　愛望','test27な人は誰？');
INSERT INTO sample (name,question) VALUES ('渡部　ありさ','test28な人は誰？');
INSERT INTO sample (name,question) VALUES ('ファン・カウ・ファウ','test29な人は誰？');
INSERT INTO sample (name,question) VALUES ('谷川先生','test30な人は誰？');
INSERT INTO sample (name,question) VALUES ('西原さん','test31な人は誰？');